### PR TITLE
Edits some language and adds anchors

### PR DESCRIPTION
**Pull request by annapamma**
Please see the comments on this PR for questions and issues I encountered while testing the example commands.

### CODE REVIEW

**Comment by annapamma** [comment]
```
We try to evaluate mRNA data on mRNA-derived simulations, and proteomics data on proteomics-derived simulated data.
```

I'm confused by this wording. Sincere question, are we talking about evaluating the data or the algorithms?

**Comment by annapamma** [comment]
Tested the following examples:
```
cwltool https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/rna-sim-test.yml ##evaluate rna-based deconvolution
cwltool https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/prot-sim-test.yml ##evaluate protein based deconvolution
```

They returned this error:

```
https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl: error: the following arguments are required: --simType
```

**Comment by annapamma** [comment]
Tested this example:
```
cwltool https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/mrna-prot/mrna-prot-comparison.cwl https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/mrna-prot/alg-test.ymlIssues:
```

and got this error:

```
Field `run` contains undefined reference to `//raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metricsn/ru-deconv.cwl`
```

When I visit https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/run-deconv.cwl, it returns a 404 Not Found

**Comment by annapamma** [comment]
I tested this command:

```
cwltool https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/imm-subtypes/pan-can-immune-preds.cwl https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/imm-subtypes/imm-args.yml
```

and got this error:

```
https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/imm-subtypes/pan-can-immune-preds.cwl:21:6: Source 'signatures' of type {"type": "array", "items": "File"} is incompatible
https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/imm-subtypes/pan-can-immune-preds.cwl:38:7: with sink 'signature' of type {"type": "array", "items": "string"}
```

**Comment by annapamma** [comment]
General comment:
I think it would be helpful if we added a description of the outputs from each example workflow, so users know what to expect. Once I get them running, I can add this.

**Comment by annapamma** [comment]
@sgosline 

I retried this command:

```
cwltool https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/rna-sim-test.yml ##evaluate rna-based deconvolution
```

and got the following:

```
INFO /Users/anna/venv/bin/cwltool 3.1.20211107152837
usage: https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl
       [-h] [--mrna-perms MRNA_PERMS] [--prot-algorithms PROT_ALGORITHMS]
       [--prot-perms PROT_PERMS] [--prot-sigs PROT_SIGS] [--rna-sigs RNA_SIGS]
       --simType SIMTYPE
       [job_order]
https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl: error: the following arguments are required: --simType
```

When I checked the[ input yaml](https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/rna-sim-test.yml), it does look like simType is there, so I'm not too sure what's happening?

**Comment by sgosline** [comment]
I wonder if this is a cwl version again? I'm running 3.1.20220224085855

**Comment by annapamma** [comment]
Was previously running: 3.1.20211107152837

Updated cwltool and tried again with: 3.1.20220406080846

but still getting the same error:
```
usage: https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl
       [-h] [--mrna-perms MRNA_PERMS] [--prot-algorithms PROT_ALGORITHMS]
       [--prot-perms PROT_PERMS] [--prot-sigs PROT_SIGS] [--rna-sigs RNA_SIGS]
       --simType SIMTYPE
       [job_order]
https://raw.githubusercontent.com/PNNL-CompBio/proteomicsTumorDeconv/main/metrics/data-sim/simul-data-comparison.cwl: error: the following arguments are required: --simType
```

**Comment by sgosline** [comment]
So strange! I'll look into this.

**Pull request merged**
